### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by idranme** [koishijs/koishi-plugin-messages#6]
```
{
  messageId: '7291993637397281169',
  id: '7291993637397281169',
  elements: [ Element { type: 'text', attrs: [Object], children: [] } ],
  content: '我喜欢的队伍输了'
}
```
```
2023-10-20 18:59:33 [W] chat TypeError: Cannot read properties of undefined (reading 'id')
                            at Object.fromUniversal (D:\develop\koishi-dev\node_modules\koishi-plugin-messages\lib\message.js:62:40)
                            at SyncChannel.syncHistory (D:\develop\koishi-dev\node_modules\koishi-plugin-messages\lib\channel.js:74:60)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async SyncChannel._init (D:\develop\koishi-dev\node_modules\koishi-plugin-messages\lib\channel.js:121:13)
                            at async D:\develop\koishi-dev\node_modules\koishi-plugin-messages\lib\channel.js:41:17
                            at async SyncChannel.ensure (D:\develop\koishi-dev\node_modules\koishi-plugin-messages\lib\channel.js:54:20)
```
![image](https://github.com/koishijs/koishi-plugin-messages/assets/96647698/c5437174-9e0a-404e-bc7b-32c38bf99f68)

**Comment by shigma** [comment]
这是哪个平台的消息？按理说应该包含 user 的。
