### ISSUE TITLE
Chat 无法启动 Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by ifrvn** [koishijs/koishi-plugin-messages#9]
```
2024-07-19 11:22:46 [E] app TypeError: Cannot read properties of undefined (reading 'get')
                            at new ChatService (/koishi/node_modules/koishi-plugin-chat/lib/index.js:52:20)
                            at MainScope.apply (/koishi/node_modules/@cordisjs/core/lib/index.cjs:913:24)
                            at /koishi/node_modules/@cordisjs/core/lib/index.cjs:936:49
                            at MainScope.ensure (/koishi/node_modules/@cordisjs/core/lib/index.cjs:714:18)
                            at MainScope.start (/koishi/node_modules/@cordisjs/core/lib/index.cjs:936:12)
                            at MainScope.init (/koishi/node_modules/@cordisjs/core/lib/index.cjs:748:12)
                            at new MainScope (/koishi/node_modules/@cordisjs/core/lib/index.cjs:869:12)
                            at Proxy.plugin (/koishi/node_modules/@cordisjs/core/lib/index.cjs:1081:15)
                            at Proxy.forkPlugin (/koishi/node_modules/@koishijs/loader/lib/shared.js:290:19)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

![image](https://github.com/user-attachments/assets/7b29d032-6ca5-4f7b-a51c-a4d974cefbd5)

System:
    OS: Linux 5.10 Alpine Linux
    CPU: (4) x64 Intel(R) Celeron(R) CPU  J3160  @ 1.60GHz

Binaries:
    Node: 20.14.0
    Yarn: 4.1.1

Koishi:
    Core: 4.17.10
    Console: 5.28.4

**Comment by ifrvn** [comment]
chat 4.0.3
messages 0.2.3

**Comment by shigma** [comment]
此插件尚未发布 🤣 你在插件市场装到的是一年前的旧版本。

**Comment by ifrvn** [comment]
🌿那没事了🤣
